Add common unit tests to precommit
Thanks to Calvin's pr.

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -2,27 +2,30 @@
 #
 # Pre-commit hooks
 
-LINT_EXIT_CODE=0
-CSS_EXIT_CODE=0
 
 # Lint stuff before committing
 SRC_PATTERN=".js"
-
 git diff --cached --name-only | if grep "$SRC_PATTERN"
 then
     grunt jshint:common
-    LINT_EXIT_CODE=$?
 fi
+jsLintResult=$?
 
-# Analyse css if changed
+git diff --cached --name-only | if grep "$SRC_PATTERN"
+then
+    grunt test:unit:common
+fi
+jsCommonResult=$?
+
+#Analyse css if changed
 SRC_PATTERN=".scss"
 git diff --cached --name-only | if grep "$SRC_PATTERN"
 then
     grunt analyse:common:css
-    CSS_EXIT_CODE=$?
 fi
+cssAnalysisResult=$?
 
-if [ $LINT_EXIT_CODE -ne 0 -o $CSS_EXIT_CODE -ne 0 ]
-then
-    exit 1
-fi
+
+# Exit code 1 means don't commit and 0 means do commit
+[ $jsLintResult -ne 0 ] || [ $cssAnalysisResult -ne 0 ] || [ $jsCommonResult -ne 0 ] && exit 1
+exit 0
