Revert "Linting testing take 2"

diff --git a/git-hooks/pre-push b/git-hooks/pre-push
--- a/git-hooks/pre-push
+++ b/git-hooks/pre-push
@@ -5,7 +5,7 @@
 branch=$(git symbolic-ref --short HEAD)
 
 
-conditionallyValidate() {
+conditionallyGrunt() {
 
     # check that remote branch exists
     git branch -r | if grep -q "origin/$branch$"
@@ -15,7 +15,9 @@ conditionallyValidate() {
         # run grunt task if relevant file-types are different
         git diff --cached --name-only "origin/$branch" | if grep $1
         then
-            $2
+            echo Running grunt $2 before pushing...
+            echo
+            grunt $2
         fi
 
     else
@@ -24,21 +26,37 @@ conditionallyValidate() {
         # run grunt task if symmetric difference from remote master contains relevant file-types
         git diff --name-only "origin/master..." | if grep $1
         then
-            $2
+            echo Running grunt $2 before pushing to a new branch...
+            echo
+            grunt $2
         fi
 
     fi
 }
 
+
 # Validate CSS
 CSS_SRC_PATTERN="\.scss$"
-conditionallyValidate "$CSS_SRC_PATTERN" "make validate-sass"
+conditionallyGrunt "$CSS_SRC_PATTERN" "validate:css"
+cssValidateResult1=$?
+conditionallyGrunt "$CSS_SRC_PATTERN" "validate:sass"
+cssValidateResult2=$?
 
 # Validate JS
 JS_SRC_PATTERN="\.js$"
-conditionallyValidate "$JS_SRC_PATTERN" "make validate-javascript"
+conditionallyGrunt "$JS_SRC_PATTERN" "validate:js"
+jsValidateResult=$?
 
 # Test JS
-conditionallyValidate "[^/]\+/\(app\|test\)/assets/javascripts/.*$JS_SRC_PATTERN" "make test"
+conditionallyGrunt "[^/]\+/\(app\|test\)/assets/javascripts/.*$JS_SRC_PATTERN" "test:unit"
+jsTestResult=$?
 
+
+# Exit code 1 means don't commit and 0 means do commit
+[ $cssValidateResult1 -ne 0 ] || [ $cssValidateResult2 -ne 0 ] || [ $jsValidateResult -ne 0 ] || [ $jsTestResult -ne 0 ] && exit 1
+
+# Modified version of [Sindre Sorhus's gist](https://gist.github.com/sindresorhus/7996717),
+# to run notifiy you if you need to update the pasteup package on npm.
+# changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"
+# echo $changed_files | grep 'pasteup' --quiet && node tools/messages.js pasteup
 exit 0
